### 라. 튜플(Tuple)

In [10]:
# 튜플 
t=(1,2,3,4,5)
# 튜플 인덱싱 및 슬라이싱
t1=(1,2,3)
print(t[1]) # 인덱싱
print(t[0:3]) # 슬라이싱

2
(1, 2, 3)


In [11]:
# 튜플 병합 및 반복
a=(1,2)
b=(3,4,5)
c=a+b
print(d)
d=a*3
print(d)

[1, 2, 1, 2, 1, 2]
(1, 2, 1, 2, 1, 2)


In [4]:
# 튜플 변수 할당
name=("David", "Kim")
print(name)
firstname, lastname=("David", "Kim")
print(lastname, ", ", firstname)

('David', 'Kim')
Kim ,  David


In [1]:
# 튜플 변수 값 변경 , 튜플은 값 변경 안됨
name=("David", "Kim")
name[0] = "Lee"
# print(name[0])

TypeError: 'tuple' object does not support item assignment

In [2]:
# 튜플 변경
name=("David", "Kim")
name=( "Lee")
print(name)

Lee


In [ ]:
### 마. Set

In [1]:
# 집합
set={1,1,2,3}
print(set)



{1, 2, 3}


In [2]:
# 집합 추가 및 삭제1
set={1,1,2,3}
set.add(4) # 요소 하나 추가
set

{1, 2, 3, 4}

In [10]:
# 집합 추가 및 삭제2
set={1,1,2,3}
set.update({4,5,6}) # 요소 여러 개 추가
set


{1, 2, 3, 4, 5, 6}

In [11]:
# 요소 하나 삭제
set.remove(4)
set

{1, 2, 3, 5, 6}

In [12]:
# 요소 모두 삭제
set.clear()
set

set()

In [13]:
# 집합 연산
a={1,2,3}
b={1,3,4}
# 교집합
c=a&b
print(c)
# 합집합
d=a|b
print(d)
# 차집합
e=a-b
print(e)

{1, 3}
{1, 2, 3, 4}
{2}


In [ ]:
### 바. 사전(Dictionary)

In [14]:
# 사전
test={"Kim":90, "Jeong":80, "Park":75}
test["Kim"] # 키 이용

90

In [16]:
# 사전 추가/수정/삭제
test={"Kim":90, "Jeong":80, "Park":75}
test["Jeong"]=85
test["Cho"]=95
print(test)

{'Kim': 90, 'Jeong': 85, 'Park': 75, 'Cho': 95}


In [17]:
del test["Park"]
print(test)

{'Kim': 90, 'Jeong': 85, 'Cho': 95}


In [18]:
# 키 또는 값 가져오기
test={"Kim":90, "Jeong":80, "Park":75}
print(test.keys())    # 키 가져오기
print(test.values())  # 값 가져오기

dict_keys(['Kim', 'Jeong', 'Park'])
dict_values([90, 80, 75])


In [ ]:
## 3-2. if문

In [19]:
# if문 예시
money=4000
if money==3000:
    print("KTX 타고 가자")
elif money>=5000:
    print("버스 타고 가자")
else:
    print("걍 걸어가!")

걍 걸어가!


In [20]:
# if문 예시
money=6000
if money>=10000: 
    print("KTX 타고 가자")
elif money>=5000:
    print("버스 타고 가자")
else:
    print("걍 걸어가!")

버스 타고 가자


In [25]:
## 3-3. 반복문
# 가. for문

In [26]:
# for문 기본
sum=0
for i in range(6):
    sum=sum+i
print(sum)

15


In [23]:
# for문 리스트 출력
list=["Wise", "In", "Company"]
for s in list:
    print(s)

Wise
In
Company


In [27]:
# 나. while문
# while문 기본
i=1
while i<6:
    print(i)
    i=i+1

1
2
3
4
5


In [28]:
# while문 리스트 출력
food=["apple", "banana", "bread"]
i=0
while i < len(food):
    print(food[i])
    i=i+1

apple
banana
bread


In [ ]:
# 4. numpy 함수
# 가. numpy 배열 생성

In [1]:
# numpy 배열 기본
import numpy as np
v1=np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [2]:
# 연속되거나 일정한 규칙을 가진 숫자
v1=np.arange(5)
print(v1)

[0 1 2 3 4]


In [3]:
# 연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2=np.arange(1,10,2, dtype=int)
v3=np.arange(3.5, 10.5 , 2, dtype=float)
print(v2)
print(v3)

[1 3 5 7 9]
[3.5 5.5 7.5 9.5]


In [4]:
# 제곱값 생성
v4=np.arange(1,10,2)**2
print(v4)

[ 1  9 25 49 81]


In [5]:
# 행렬만들기
v1=np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
v2=v1.reshape(2,6)
print(v2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [7]:
v3=v1.reshape(2,6, order='F')
print(v3)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [9]:
# 행렬계산
v1=np.arange(1,5).reshape(2,2)
print(v1)
print(np.add(v1,v1))        # 덧셈
print(np.subtract(v1,v1))   # 뺄셈
print(np.multiply(v1,v1))   # 곱셈
print(np.dot(v1,v1))        # 행렬연산

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [10]:
# 다차원 배열에서 요소의 최대값 및 최소값 반환
v3=np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4=np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amin(v4))
print(v3.dtype)
print(v4.shape)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)
